web/router.ex
defmodule Support.Router do
  use Support.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Support.CurrentUser
    plug :put_user_token
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :admin do
    plug :require_current_user
  end

  scope "/", Support do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/register", RegistrationController, :new
    post "/register", RegistrationController, :create

    get "/login", SessionController, :new
    post "/login", SessionController, :create
    delete "/logout", SessionController, :delete

    resources "/issues", IssueController
    resources "/users", UserController, except: [:new, :edit]
  end

  scope "/admin", Support do
    pipe_through [:browser, :admin]
    resources "/users", UserController, except: [:new, :edit]
  end

  defp put_user_token(conn, _) do
    if current_user = conn.assigns[:current_user] do
      token = Phoenix.Token.sign(conn, "user socket", current_user.id)
      assign(conn, :user_token, token)
    else
      conn
    end
  end

  defp require_current_user(conn, _) do
    import Phoenix.Controller, only: [put_flash: 3, redirect: 2]
    if conn.assigns.current_user do
      conn
    else
      conn
      |> put_flash(:error, "unauthorized")
      |> redirect(to: "/")
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", Support do
  #   pipe_through :api
  # end
end

web/templates/page/hello.html.eex
<h2>Hello <%= inspect @conn.assigns %></h2>

web/templates/page/index.html.eex
<div class="jumbotron">
  <%= if @current_user do %>
    <h2>Welcome <%= @current_user.name %></h2>
    <%= link "Logout", to: session_path(@conn, :delete),
        method: :delete,
        class: "btn btn-danger" %>
  <% else %>
    <h2>Welcome Guest</h2>
    <%= link "Login", to: session_path(@conn, :new),
        class: "btn btn-default" %>
    or
    <%= link "Register", to: registration_path(@conn, :new),
        class: "btn btn-primary" %>
  <% end %>
  <p class="lead">A productive web framework that<br />does not compromise speed and maintainability.</p>
</div>

<div class="row marketing">
  <div class="col-lg-6">
    <h4>Resources</h4>
    <ul>
      <li>
        <a href="http://phoenixframework.org/docs/overview">Guides</a>
      </li>
      <li>
        <a href="http://hexdocs.pm/phoenix">Docs</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix">Source</a>
      </li>
    </ul>
  </div>

  <div class="col-lg-6">
    <h4>Help</h4>
    <ul>
      <li>
        <a href="http://groups.google.com/group/phoenix-talk">Mailing list</a>
      </li>
      <li>
        <a href="http://webchat.freenode.net/?channels=elixir-lang">#elixir-lang on freenode IRC</a>
      </li>
      <li>
        <a href="https://twitter.com/elixirphoenix">@elixirphoenix</a>
      </li>
    </ul>
  </div>
</div>